version: 2

models:
  - name: stg_complications_and_deaths
    columns:
      - name: hospital_id
        tests:
          - not_null
      - name: measure_id
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - hospital_id
              - measure_id

  - name: stg_hospital_general_info
    columns:
      - name: hospital_id
        tests:
          - not_null
          - unique